//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int id { get; set; }
        public int idCoach { get; set; }
        public int idService { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Service Service { get; set; }
    }
}
