//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SeasonTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeasonTicket()
        {
            this.Visitings = new List<Visiting>();
        }
    
        public int idSeasonTicket { get; set; }
        public Nullable<int> idService { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idCoach { get; set; }
        [Display(Name = "Количество занятий")]
        public int classesTotal { get; set; }
        public Nullable<int> classesLeft { get; set; }

        [DataType(DataType.Date), Required]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата начала")]
        public System.DateTime dateStart { get; set; }

        [DataType(DataType.Date), Required]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата окончания")]
        public System.DateTime dateEnd { get; set; }
        public Nullable<int> saleClasses { get; set; }
        public Nullable<int> saleAge { get; set; }
        public Nullable<int> saleСonstantСlient { get; set; }
        public Nullable<float> totalCost { get; set; }

        [Required]
        public virtual Client Client { get; set; }
        [Required]
        public virtual Coach Coach { get; set; }
        [Required]
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Visiting> Visitings { get; set; }
    }
}
